[project]
name = "constrained-ot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.0",
    "matplotlib>=3.10.3",
    "numpy>=2.3.2",
    "ott-jax>=0.5.1",
    "scikit-learn>=1.7.2",
    "scipy>=1.16.1",
    "tqdm>=4.67.1",
]
